version: "3.8"

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=${NODE_ENV}
